# Generated by Django 3.0.7 on 2020-06-27 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200626_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[(0, 'Practice'), (1, 'Lecture'), (2, 'Info')], default=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 17, 49, 18, 298844)),
        ),
    ]
