# Generated by Django 3.0.7 on 2020-06-30 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200630_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='doc',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 17, 28, 12, 499175)),
        ),
    ]
